version: '3.5'
services:
  db-postgres-pokebank:
    container_name: pg-pokebank
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pokebankdb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "9000:5432"
  api:
    container_name: pokebank-api
    image: node:18-alpine
    command: npm start
    environment:
      DB_HOST: db-postgres-pokebank
      DB_USER: pguser
      DB_PASSWORD: pgpassword
      DB_NAME: pokebankdb
    depends_on:
      - db-postgres-pokebank
    working_dir: /src
    volumes:
      - .:/src
      - ./node_modules:/src/node_modules
    ports:
      - "3000:3000"
volumes:
  data:
