version: '3.5'

services:
  postgres:
    container_name: postgres-pokebank
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pokebank
    volumes:
      - ./data:/data/postgres
    ports:
      - "9000:5432"
  
  api:
    container_name: pokebank-api
    image: node:18-alpine
    command: npm start
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pokebank
    working_dir: /src
    volumes:
      - .:/src
      - ./node_modules:/src/node_modules
    ports:
      - "3000:3000"